      - name: Setup SDK
        run: |
          # Tải SDK từ nguồn chính thức của Theos (định dạng zip để an toàn hơn)
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mkdir -p /opt/theos/sdks
          # Chuyển đúng thư mục SDK 14.5 vào Theos
          mv sdks-master/iPhoneOS14.5.sdk /opt/theos/sdks/
