name: Build DuyLocIosCheat

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Theos & Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential perl git curl libssl-dev
          # Tạo thư mục và clone Theos chính xác
          sudo mkdir -p /opt/theos
          sudo git clone --recursive https://github.com/theos/theos.git /opt/theos
          sudo chown -R $USER:$GROUP /opt/theos
          
          # Cài đặt Toolchain vào đúng vị trí
          curl -LO https://github.com/kabiroberai/theos-toolchain-linux/releases/download/v2.0.0/toolchain-linux-arm64.tar.gz
          mkdir -p /opt/theos/toolchain/linux/iphone
          tar -xf toolchain-linux-arm64.tar.gz -C /opt/theos/toolchain/linux/iphone --strip-components=1

          - name: Setup SDK & Toolchain
         run: |
          # Tải SDK 14.5
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip -q master.zip
          mkdir -p /opt/theos/sdks
          mv sdks-master/iPhoneOS14.5.sdk /opt/theos/sdks/
          rm -rf sdks-master master.zip

          # Tải Toolchain bằng link trực tiếp và ép buộc chuyển hướng (Fix lỗi dòng 155)
          mkdir -p /opt/theos/toolchain/linux/iphone
          curl -L "https://github.com/theos/toolchain/releases/download/linux-arm64/toolchain-linux-arm64.tar.gz" | tar -xz -C /opt/theos/toolchain/linux/iphone --strip-components=1
    

      - name: Build Tweak
        run: |
          export THEOS=/opt/theos
          make package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DuyLocIosCheat-Dylib
          path: |
            .theos/obj/debug/*.dylib
            packages/*.deb
