name: Build DuyLocIosCheat

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Theos environment
        uses: theos/setup-theos-action@v1.0.3

      - name: Download iOS SDK
        run: |
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip -q master.zip
          mv sdks-master/iPhoneOS14.5.sdk $THEOS/sdks/
          rm -rf sdks-master master.zip

      - name: Build Tweak
        run: |
          make package FINALPACKAGE=1
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DuyLocIosCheat-Dylib
          path: |
            .theos/obj/debug/*.dylib
            packages/*.deb
